from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from utils import setup_logging

plt.switch_backend("Agg")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate walk-forward prediction outputs.")
    parser.add_argument(
        "--predictions",
        default="reports/predictions_walkforward.csv",
        help="Path to predictions file generated by train_model.py.",
    )
    parser.add_argument(
        "--output",
        default="reports/evaluation_summary.csv",
        help="Output CSV for aggregated evaluation metrics.",
    )
    parser.add_argument(
        "--plots-dir",
        default="reports/plots",
        help="Output directory for generated plots.",
    )
    return parser.parse_args()


def _max_drawdown(returns: pd.Series) -> float:
    if returns.empty:
        return 0.0
    equity = (1.0 + returns).cumprod()
    peak = equity.cummax()
    drawdown = equity / peak - 1.0
    return float(drawdown.min())


def _sharpe(returns: pd.Series, periods_per_year: int = 252) -> float:
    if returns.empty:
        return 0.0
    std = returns.std(ddof=0)
    if std == 0 or np.isnan(std):
        return 0.0
    return float(np.sqrt(periods_per_year) * (returns.mean() / std))


def _aggregate(group: pd.DataFrame) -> pd.Series:
    strategy = group["strategy_return"]
    benchmark = group["benchmark_return"]
    return pd.Series(
        {
            "rows": int(len(group)),
            "hit_rate": float((group["y_pred"] == group["y_true"]).mean()),
            "strategy_cum_return": float((1.0 + strategy).prod() - 1.0),
            "benchmark_cum_return": float((1.0 + benchmark).prod() - 1.0),
            "strategy_sharpe": _sharpe(strategy),
            "benchmark_sharpe": _sharpe(benchmark),
            "strategy_max_drawdown": _max_drawdown(strategy),
            "benchmark_max_drawdown": _max_drawdown(benchmark),
        }
    )


def _build_cumulative_returns(preds: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for (model, symbol), group in preds.groupby(["model", "symbol"]):
        g = group.sort_values("timestamp").copy()
        g["strategy_equity"] = (1.0 + g["strategy_return"]).cumprod()
        g["benchmark_equity"] = (1.0 + g["benchmark_return"]).cumprod()
        g["model"] = model
        g["symbol"] = symbol
        rows.append(g[["timestamp", "model", "symbol", "strategy_equity", "benchmark_equity"]])
    if not rows:
        return pd.DataFrame(
            columns=["timestamp", "model", "symbol", "strategy_equity", "benchmark_equity"]
        )
    return pd.concat(rows, ignore_index=True)


def _save_symbol_plots(cum_df: pd.DataFrame, plots_dir: Path) -> None:
    if cum_df.empty:
        return
    plots_dir.mkdir(parents=True, exist_ok=True)

    for symbol, group in cum_df.groupby("symbol"):
        fig, ax = plt.subplots(figsize=(10, 5))
        benchmark = group[["timestamp", "benchmark_equity"]].drop_duplicates().sort_values("timestamp")
        ax.plot(
            benchmark["timestamp"],
            benchmark["benchmark_equity"],
            label=f"{symbol} benchmark",
            linewidth=2.5,
            linestyle="--",
            color="black",
        )
        for model, model_group in group.groupby("model"):
            mg = model_group.sort_values("timestamp")
            ax.plot(mg["timestamp"], mg["strategy_equity"], label=model, linewidth=1.8)

        ax.set_title(f"Cumulative Return by Model - {symbol}")
        ax.set_xlabel("Time")
        ax.set_ylabel("Equity Curve (start=1.0)")
        ax.grid(True, alpha=0.3)
        ax.legend()
        fig.tight_layout()
        fig.savefig(plots_dir / f"cumulative_{symbol}.png", dpi=160)
        plt.close(fig)


def main() -> None:
    setup_logging()
    args = parse_args()
    predictions_path = Path(args.predictions)
    output_path = Path(args.output)
    plots_dir = Path(args.plots_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    preds = pd.read_csv(predictions_path, parse_dates=["timestamp"])
    if preds.empty:
        raise ValueError(f"No predictions found in {predictions_path}")

    by_model = preds.groupby("model").apply(_aggregate, include_groups=False).reset_index()
    by_symbol = (
        preds.groupby(["model", "symbol"])
        .apply(_aggregate, include_groups=False)
        .reset_index()
    )
    by_symbol_pivot = by_symbol.pivot(
        index="symbol", columns="model", values="strategy_cum_return"
    ).reset_index()
    cum_df = _build_cumulative_returns(preds)
    _save_symbol_plots(cum_df, plots_dir)

    by_model.to_csv(output_path, index=False)
    by_symbol_path = output_path.with_name("evaluation_by_model_symbol.csv")
    by_symbol.to_csv(by_symbol_path, index=False)
    by_symbol_pivot_path = output_path.with_name("evaluation_by_symbol_pivot.csv")
    by_symbol_pivot.to_csv(by_symbol_pivot_path, index=False)
    cum_path = output_path.with_name("cumulative_returns_by_model_symbol.csv")
    cum_df.to_csv(cum_path, index=False)

    print(f"Saved model evaluation: {output_path}")
    print(f"Saved model-symbol evaluation: {by_symbol_path}")
    print(f"Saved symbol pivot table: {by_symbol_pivot_path}")
    print(f"Saved cumulative return table: {cum_path}")
    print(f"Saved plots in: {plots_dir}")
    print(by_model.to_string(index=False))


if __name__ == "__main__":
    main()
